platform :ios, '9.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end

target 'RxMoyaExample' do

pod 'RxCocoa',    '~> 3.0.0'

pod 'Moya-ModelMapper/RxSwift', '~> 4.0.0-beta.3'
pod 'RxOptional', '~> 3.1.2'

end
