# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RxDataSourcesExample' do

pod "RxDataSources"
pod "NSObject+Rx"

end

