platform :ios, '8.0'
use_frameworks!

target 'RxWebKitExample' do

pod 'RxWebKit', "~> 0.3.3"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end

